#!/usr/bin/env bash

#================================CABEÇALHO===================================|
#
#  AUTOR
#     Felipe Fernandes <felipefernandesgsc@gmail.com>
#
#  PROGRAMA
#     NetChat
#
#  DATA DE CRIAÇÃO
#     31/12/2018
#
#  DESCRIÇÃO
#     Cria um chat entre dois ou mais computadores por meio do programa NetCat
#
#  FUNCIONAMENTO
#     O usuário que hospedará o chat ficará ouvindo as informações digitadas
#    em uma porta selecionada pelo usuário, os outros indivíduos se conectarão
#    no usuário Host por meio do IP do Host e pela porta definida.
#
#  CHANGELOG
#     31/12/2018 - Criação de estrutura do programa; criação do menu help,
#    função de sair, logo do programa, função de conectar em um chat, função
#    de criar um chat e o manual de funcionamento.
#     02/01/2018 - Adicionado teste de verificação se o programa existe na má-
#    quina.
#     11/01/2019 - Adicionado a função de ter um nome no chat.
#
#============================================================================|

#==========================================TESTES

#Fazer teste se o programa Netcat está instalado ou não no sistema.
verificar_programa=`builtin type -P nc`
  if [ -z "${verificar_programa}" ]
    then
    clear
    echo -e "O programa Netcat não está instalado em sua máquina \nQuer instala-lo em sua máquina? [s/n] (certifique estar em modo super usuário)"
    read instalar_netcat
	case $instalar_netcat in
	s|S)
	apt-get install netcat ;;
	n|N)
	echo -e "\nFinalizando programa..." ; exit ;;
	*)
	echo -e "\nOpção inválida \nFinalizando programa..." ; exit ;;
	esac
  fi
#================================================

#=========================================FUNÇÕES
_LOGO()
{
cat << END
╔╗╔╔═╗╔╦╗╔═╗╦ ╦╔═╗╔╦╗   |		  | 
║║║║╣  ║ ║  ╠═╣╠═╣ ║    |    Bem-Vindo    | -h ou --help para ver as opções
╝╚╝╚═╝ ╩ ╚═╝╩ ╩╩ ╩ ╩    |		  |
=============================================================================

END
}

_HELP()
{
less << END

 -h|--help
    Imprime esta lista de comandos.

 -m|--manual
    Imprime o manual de funcionamento do programa.

 -r|--hostear
    Cria um chat.

 -c|--conectar
    Se conecta a um chat existente.

 -s|--sair
    Sai do programa.

END
echo
}

_MANUAL()
{
less << END

    Funcionamento

   Para que ocorra o funcionamento do chat é necessário que um indivíduo crie o
  chat (dizendo por qual porta ocorrerá a comunicação) e outro outro indíviduo
  acesse o chat (dizendo qual o IP do criador e qual a porta que foi escolhida
  para a comunicação).

   O programa utiliza o Netcat para realizar a troca de informações entre os
  usuários, por tal motivo o programa chama-se NetChat, sendo um trocadilho com
  a maneira que ele funciona.

END
}

_CRIAR_CHAT()
{
read -p "Digite o seu nome: " nome
read -p "Digite a porta que será ouvida para criar o chat: " porta_abrir
mawk -W interactive -v nome="${nome}: " '$0=nome $0' | nc -vlp ${porta_abrir}
}

_CONECTAR_CHAT()
{
read -p "Digite o seu nome: " nome
read -p "Digite o IP do host do chat: " ip_host
read -p "Digite a porta do chat: " porta_chat

mawk -W interactive -v nome="${nome}: " '$0=nome $0' | nc ${ip_host} ${porta_chat}
}
#================================================

#=========================================INICIAL
   clear
   _LOGO
   read tarefa

      until [ $tarefa = "--sair" ] 2> /dev/null || [ $tarefa = "-s" ] 2> /dev/null ; do


       case $tarefa in
	-h|--help)
	_HELP ;;

	-m|--manual)
	_MANUAL ;;

	-r|--hostear)
	_CRIAR_CHAT ;;

	-c|--conectar)
	_CONECTAR_CHAT ;;

	*)
	echo -e "Digite alguma opção válida \n" ;;
       esac


      read tarefa
      done

#================================================
