#!/bin/bash

#==============================[ CABEÇALHO ]=================================|
#  AUTOR
#     Felipe Fernandes <felipefernandesgsc@gmail.com>
#
#  PROGRAMA
#	  LM-Login
#
#  DATA DE CRIAÇÃO
#     18/05/2019
#
#  DESCRIÇÃO
#     Realiza o login para o acesso aos registros de arquivos de monitoramento
#
#  FUNCIONAMENTO
#     O programa realiza o  login utilizando a interface gráfico "dialog", seu
#    sistema realiza a comparação de login e senha com o banco de dados criado
#    pelo programa LM-Management. Após o login o programa apresenta  uma sele-
#    ção de serviços  que podem ser acessados,  seja de monitoramento de rede,
#    seja de suporte ou de registro de usuários.
#
#  CHANGELOG
#     www.github.com/Mewbi/tcc-senai/LM-Login/changelog.txt
#============================================================================|

#==============================[ VARIÁVEIS ]=================================|
banco="banco-logins.txt"
caminho="$HOME/tcc-senai/"
#============================================================================|

#==============================[ TESTES ]====================================|
#Verificar se Dialog está instalado
inst_dialog=$(type -P dialog)
   if [ ! -n "$inst_dialog" ] ; then
      echo -e "\tDialog não está instalado...
\tInstale-o primeiramente para o programa funcionar"
	  exit
   fi
#============================================================================|

#==============================[ INICIAL ]===================================|
#Loop para realização do Login
while true ; do
#Recebendo Login e senha do usuário
login=$(
	dialog --stdout --title "Login" --backtitle "Sistema de Login" --begin 2 2 \
		   --inputbox "Digite seu login" 0 0\
		   --and-widget \
		   --begin 2 35 \
		   --insecure --passwordbox "Digite sua senha" 0 0
)

user=$(echo $login | cut -d ' ' -f1)
pass=$(echo $login | cut -d ' ' -f2)


#Verificando usuário no banco de dados
usuario=$(grep -w "$user" "$banco" | cut -d: -f1)
   if [ -n "$usuario" ] ; then

	  #Pega a senha criptografada no banco de dados
      senha=$(grep -w "$user" "$banco" | cut -d: -f3)
	  #Criptografa a senha inserida
	  salt=$(grep -w "$user" "$banco" | cut -d: -f2)
	  pass=$(echo "${pass}${salt}" | sha256sum | awk '{print $1}')

		#Verifica se o usuário e a senha estão corretos
	  	if [ "$usuario" = "$user" ] && [ "$senha" = "$pass" ] ; then
			dialog --stdout --title "Login Aceito" \
		   	       --msgbox "Login realizado com sucesso!" 5 35
			break
		else
    		dialog --stdout --title "Login Incorreto" \
		   	 	--msgbox "Verifique seu Login e Senha" 5 35
		fi
		
   else
      dialog --stdout --title "Erro" \
	  	     --msgbox "Login não registrado" 5 30
   fi

done


#Menu de Seleção
while : ; do
opcao=$(dialog \
	--stdout \
	--menu 'Selecione uma Opção' \
	0 0 0 \
	LM-MRI 'Acessar Monitoramento' \
	LM-CSerivce 'Acessar Central de Configurações de Serviços' \
	LM-NetChat 'Acessar Chat de Suporte' \
	LM-SSHost 'Realizar Acesso a Outras Máquinas' \
	LM-Management 'Acessar Gerenciamento de Usuários' \
	Contato 'Entrar em Contato com Suporte' \
	Sair 'Sair do Programa' \
)


#Acessando as Opções
case $opcao in

   LM-MRI)
   bash ${caminho}LM-MRI/monLAN.sh
   ;;

   LM-CService)
   bash ${caminho}LM-CService/CentralConf.sh
   ;;

   LM-NetChat)
   bash ${caminho}LM-NetChat/NetChat
   ;;

   LM-SSHost)
   bash ${caminho}LM-SSHost/LM-SSHost
   ;;

   LM-Management)
   bash ${caminho}LM-Management/LM-Management
   ;;

   Contato)
   dialog \
   --stdout --title "E-mail para contato" \
   --msgbox "felipefernandesgsc@gmail.com" 5 40
   ;;

   Sair)
   exit 0
   ;;
esac

done
#============================================================================|
