#!/usr/bin/env bash

#==============================[ CABEÇALHO ]=================================|
#  AUTOR
#     Felipe Fernandes <felipefernandesgsc@gmail.com>
#
#  PROGRAMA
#	  LM-Management
#
#  DATA DE CRIAÇÃO
#     18/05/2019
#
#  DESCRIÇÃO
#	  Realiza o gerenciamento  de usuários para o acesso aos serviços de moni-
#   toramento de redes.
#
#  FUNCIONAMENTO
#	  O programa cria e remove usuários que terão acesso aos serviços de moni-
#   toramento de redes, como também realiza o direcionamento para a sessão de
#   login, para ter acesso a outros programas que realizam a supervisão da(s)
#   rede(s) analisada(s).
#
#  CHANGELOG
#     www.github.com/Mewbi/tcc-senai/LM-Managemente/changelog.txt
#============================================================================|

#==============================[ VARIÁVEIS ]=================================|
banco='banco-logins.txt'
#============================================================================|

#==============================[ TESTES ]====================================|
# Verifica existência do banco de dados
[ ! -e "$banco" ] && > "$banco"
#============================================================================|


#==============================[ FUNÇÕES ]===================================|

#============================================================================|

#==============================[ INICIAL ]===================================|
while : ; do
   read -p "Digite um comando para executar uma tarefa: " tarefa
      case $tarefa in
	     -h|--help)
		 echo "menu help" ;;
		 
		 
		 -m|--manual)
		 echo "manual de uso" ;;
		 
		 
		 -r|--registrar)
		 echo -e "\n\t Registro"
		 echo -e "\nDigite o login e senha para a nova conta\n"
		 
		 while : ; do #Loop para verificar login
		 read -p "Login: " login
		 login="${login,,}" #Convertendo para minusculo
		      #Checagem de existência no banco de dados
			  grep -qo "${login}" "$banco" \
			  && { echo -e "\nLogin existente. \nPor favor digite um novo login.\n"; continue;} \
			  || { break;}
		 done
		 
		 while : ; do #Loop para verificar a senha
		 read -s -p "Senha: " senha ; echo
		 read -s -p "Confirmar senha: " senha2 ; echo
		      if [ "$senha" != "$senha2" ] ; then
			     echo -e "\nSenhas não estão iguais. \nPor favor redigite-as.\n"
				 continue
				    else
					break
			  fi
		 done
	      
		 #Senha=Senha+salt+hash
	     salt=$(tr -dc _A-Z-a-z-0-9 < /dev/urandom | head -c 8; echo)
		 senha=$(echo "${senha}${salt}" | sha256sum | awk '{print $1}')
		 echo "${login}:${salt}:${senha}" >> "$banco" && { echo -e "\nUsuário criado com sucesso."; sleep 3;}
		 ;;
		 
		 
		 -d|--deletar)
		 echo
		 ;;
		 
		 -l|--login)
		 ./LM-Login
		 exit
		 ;;
		 
		 -s|--sair)
		 break ;;
		 
	  esac
done
#============================================================================|
